version: '3.7'

services:
    python:
        build: ./
        container_name: dbd_python
        tty: true
        restart: always
        ports:
            - "8080:8080"
        working_dir: /dbdv2

        volumes:
            - ./dbdv2:/dbdv2
            - ./chromedriver:/usr/bin/chromedriver
              #- ./dags:/root/airflow/dags
              #- ./airflow.cfg:/root/airflow/airflow.cfg
        depends_on:
            - database

    django:
        build: ./django_api
        container_name: dbd_django
        tty: true
        restart: always
        ports:
            - "8000:8000"
        working_dir: /frontend

        volumes:
            - ./django_api/frontend:/frontend
        depends_on:
            - database
        command: ./wait-for-it.sh -t 0 -h dbd_db -p 3306 -- ./run.sh
            
    database:
        image: mariadb
        container_name: dbd_db
        tty: true
        restart: always
        ports:
            - "3309:3306"
        env_file:
            - .env
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
            - ./dbd.sql:/tmp/dbd.sql
            - ./zipcodes.sql:/tmp/zipcodes.sql
            - ./database:/var/lib/mysql
