version: '3.7'

services:
    python_webserver:
        build: ./
        container_name: dbd_webserver
        tty: true
        restart: always
        ports:
            - "8080:8080"
        working_dir: /dbdv2

        volumes:
            - ./dbdv2:/dbdv2
            - ./chromedriver:/usr/bin/chromedriver
            - ./dags:/root/airflow/dags
            - ./logs:/root/airflow/logs
            - ./configs/airflow.cfg:/root/airflow/airflow.cfg
        depends_on:
            - database
        command: ./wait-for-it.sh -t 0 -h dbd_db -p 3306 -- ./start.sh
              #command: ./start.sh

    python_scheduler:
        build: ./
        container_name: dbd_scheduler
        tty: true
        restart: always
        working_dir: /dbdv2

        volumes:
            - ./dbdv2:/dbdv2
            - ./chromedriver:/usr/bin/chromedriver
            - ./dags:/root/airflow/dags
            - ./logs:/root/airflow/logs
            - ./configs/airflow.cfg:/root/airflow/airflow.cfg
        depends_on:
            - database
              #command: ./start2.sh
        command: ./wait-for-it.sh -t 0 -h dbd_db -p 3306 -- ./start2.sh

    django:
        build: ./django_api
        container_name: dbd_django
        tty: true
        restart: always
        ports:
            - "8000:8000"
        working_dir: /frontend

        volumes:
            - ./django_api/frontend:/frontend
            - ./dbdv2/data_access/customer_csv:/frontend/csv_files/
            - ./dbdv2/data_access/company_pdf:/frontend/pdf_files/
        depends_on:
            - database
             #command: ./wait-for-it.sh -t 0 -h dbd_db -p 3306 -- ./run.sh
        command: ./run.sh
            

    database:
        image: mariadb
        container_name: dbd_db
        tty: true
        restart: always
        ports:
            - "3309:3306"
        env_file:
            - .env
        volumes:
            - ./database:/var/lib/mysql
            - ./configs/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./sql:/docker-entrypoint-initdb.d

    php:
        image: adminer
        container_name: php_adminer
        restart: always
        ports:
            - "8083:8080"
