# Generated by Django 3.0.1 on 2020-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbdcompany',
            fields=[
                ('dbd_id', models.CharField(db_column='DBD_ID', max_length=45, primary_key=True, serialize=False)),
                ('dbd_type', models.CharField(blank=True, db_column='DBD_TYPE', max_length=45, null=True)),
                ('dbd_name_th', models.CharField(blank=True, db_column='DBD_NAME_TH', max_length=255, null=True)),
                ('dbd_name_en', models.CharField(blank=True, db_column='DBD_NAME_EN', max_length=255, null=True)),
                ('dbd_registration_date', models.DateField(blank=True, db_column='DBD_REGISTRATION_DATE', null=True)),
                ('dbd_status', models.CharField(blank=True, db_column='DBD_STATUS', max_length=100, null=True)),
                ('dbd_registration_money', models.BigIntegerField(blank=True, db_column='DBD_REGISTRATION_MONEY', null=True)),
                ('dbd_address', models.TextField(blank=True, db_column='DBD_ADDRESS', null=True)),
                ('dbd_objective', models.TextField(blank=True, db_column='DBD_OBJECTIVE', null=True)),
                ('dbd_street', models.TextField(blank=True, db_column='DBD_STREET', null=True)),
                ('dbd_subdistrict', models.TextField(blank=True, db_column='DBD_SUBDISTRICT', null=True)),
                ('dbd_district', models.TextField(blank=True, db_column='DBD_DISTRICT', null=True)),
                ('dbd_province', models.TextField(blank=True, db_column='DBD_PROVINCE', null=True)),
                ('dbd_zipcode', models.CharField(blank=True, db_column='DBD_ZIPCODE', max_length=5, null=True)),
                ('dbd_business_type_code', models.TextField(blank=True, db_column='DBD_BUSINESS_TYPE_CODE', null=True)),
                ('dbd_business_type', models.TextField(blank=True, db_column='DBD_BUSINESS_TYPE', null=True)),
                ('dbd_directors', models.TextField(blank=True, db_column='DBD_DIRECTORS', null=True)),
            ],
            options={
                'db_table': 'dbdcompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbdNewQuery',
            fields=[
                ('dbd_company_id', models.CharField(db_column='DBD_COMPANY_ID', max_length=45, primary_key=True, serialize=False)),
                ('dbd_typecode', models.CharField(blank=True, db_column='DBD_TYPECODE', max_length=45, null=True)),
                ('dbd_status', models.TextField(blank=True, db_column='DBD_STATUS', null=True)),
                ('dbd_last_run', models.DateTimeField(blank=True, db_column='DBD_LAST_RUN', null=True)),
                ('dbd_ignore', models.IntegerField(blank=True, db_column='DBD_IGNORE', null=True)),
                ('dbd_change', models.IntegerField(blank=True, db_column='DBD_CHANGE', null=True)),
                ('c_dbd_name_th', models.TextField(blank=True, db_column='C_DBD_NAME_TH', null=True)),
                ('c_dbd_status', models.TextField(blank=True, db_column='C_DBD_STATUS', null=True)),
                ('c_dbd_objective', models.TextField(blank=True, db_column='C_DBD_OBJECTIVE', null=True)),
                ('c_dbd_business_type', models.TextField(blank=True, db_column='C_DBD_BUSINESS_TYPE', null=True)),
                ('c_dbd_address', models.TextField(blank=True, db_column='C_DBD_ADDRESS', null=True)),
            ],
            options={
                'db_table': 'dbd_new_query',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbdQuery',
            fields=[
                ('dbd_company_id', models.CharField(db_column='DBD_COMPANY_ID', max_length=45, primary_key=True, serialize=False)),
                ('dbd_typecode', models.CharField(blank=True, db_column='DBD_TYPECODE', max_length=45, null=True)),
                ('dbd_status', models.TextField(blank=True, db_column='DBD_STATUS', null=True)),
                ('dbd_last_run', models.DateTimeField(blank=True, db_column='DBD_LAST_RUN', null=True)),
                ('dbd_ignore', models.IntegerField(blank=True, db_column='DBD_IGNORE', null=True)),
                ('dbd_change', models.IntegerField(blank=True, db_column='DBD_CHANGE', null=True)),
                ('c_dbd_name_th', models.TextField(blank=True, db_column='C_DBD_NAME_TH', null=True)),
                ('c_dbd_status', models.TextField(blank=True, db_column='C_DBD_STATUS', null=True)),
                ('c_dbd_objective', models.TextField(blank=True, db_column='C_DBD_OBJECTIVE', null=True)),
                ('c_dbd_business_type', models.TextField(blank=True, db_column='C_DBD_BUSINESS_TYPE', null=True)),
                ('c_dbd_address', models.TextField(blank=True, db_column='C_DBD_ADDRESS', null=True)),
            ],
            options={
                'db_table': 'dbd_query',
                'managed': False,
            },
        ),
    ]
